bind = $mainMod, Return, exec, kitty --override background_opacity=0
decoration {
    rounding = 6
    dim_special = 0.45
    blur {
        enabled = true
        ignore_opacity = true
        special = false
        noise = 0.00
        size = 0
        passes = 1
        vibrancy = 0.20
        glass_lensing = 20
        glass_edge_softness = 9
        glass_dimming = 0.0
        glass_tint_strength = 0.0
        glass_specular_strength = 0
        glass_light_strength = 0.2
        glass_shadow_strength = 0.2
        glass_ambient_strength = 1

        brightness = 1.0
        vibrancy_darkness = 1
    }
}
