bind = $mainMod, Z, exec, notify-send --action="REPLY=Open" --action="dismiss=Mark As " "Alice" "Hey, are you free for a call? Notification description lorem ipsum dolor sit ament."
bind = $mainMod, X, exec, pkill quickshell; quickshell
bind = $mainMod, A, exec, qs -c default ipc call shell toggleControlCenter
bind = $mainMod, N, exec, qs -c default ipc call shell toggleNotificationCenter

layerrule = blur_popups on, match:namespace qsbar
# layerrule = ignore_alpha 0, match:namespace qsbar

layerrule {
    name = quickshell-notification-center-blur
    match:namespace = quickshell:(notification-center)$
    blur = on
    ignore_alpha = 0.2
    xray = 0
}

layerrule {
    name = quickshell-notifications
    match:namespace = quickshell:(notifications)$
    blur = on
    ignore_alpha = 0.1
    # no_anim = 1
    # xray = 0
}

layerrule {
    name = quickshell-control-center-blur
    match:namespace = quickshell:(control-center)$
    blur = on
    ignore_alpha = 0.10
    # xray = 0
}

layerrule {
    name = quickshell-widgets-blur
    match:namespace = quickshell:(notification-actions|notification-dismiss)$
    blur = on
    ignore_alpha = 0.1
    no_anim = 1
}

