bind = $mainMod, Z, exec, notify-send --action="REPLY=Open" --action="dismiss=Mark As " "Alice" "Hey, are you free for a call? Notification description lorem ipsum dolor sit ament."
bind = $mainMod, X, exec, pkill quickshell; quickshell
bind = $mainMod, A, exec, qs ipc call shell toggleControlCenter
bind = $mainMod, N, exec, qs ipc call shell toggleNotificationCenter
bind = $mainMod, B, exec, qs ipc --any-display call shell toggleBarVisibility

layerrule {
    name = quickshell-control-center-tile-1x1-blur
    match:namespace = ^quickshell:control-center-tile-1x1$
    blur = on
    rounding = 35
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-control-center-tile-2x1-blur
    match:namespace = ^quickshell:control-center-tile-2x1$
    blur = on
    rounding = 33
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-control-center-tile-2x2-blur
    match:namespace = ^quickshell:control-center-tile-2x2$
    blur = on
    rounding = 37
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-control-center-tile-4x1-blur
    match:namespace = ^quickshell:control-center-tile-4x1$
    blur = on
    rounding = 27
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-control-center-footer-blur
    match:namespace = ^quickshell:control-center-footer$
    blur = on
    rounding = 17
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-desktop-widgets-blur
    match:namespace = ^quickshell:desktop-widget-(calendar|weather):.*
    blur = on
    rounding = 25
    rounding_power = 2
    ignore_alpha = 0.10
    no_anim = 1
}

layerrule {
    name = quickshell-menu-blur
    match:namespace = ^quickshell:menu$
    rounding = 13
    blur = on
    ignore_alpha = 0.1
    no_anim = 1
    xray = 0
}

layerrule {
    name = quickshell-notification-center-blur
    match:namespace = quickshell:(notification-center)$
    blur = on
    ignore_alpha = 0.2
    xray = 0
}

layerrule {
    name = quickshell-notification-popup-backdrop-blur
    match:namespace = ^quickshell:notification-popup-backdrop$
    blur = on
    rounding = 14
    rounding_power = 2
    ignore_alpha = 0.0
    no_anim = 1
    xray = 0
}

windowrule {
    name = quickshell-alert
    match:title = ^quickshell:alert$
    float = on
    center = on
    rounding = 26
    rounding_power = 2
    no_shadow = on
}

layerrule {
    name = quickshell-widgets-blur
    match:namespace = quickshell:(notification-actions|notification-dismiss)$
    blur = on
    ignore_alpha = 0.1
    no_anim = 1
}
