$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$mainMod = ALT

permission = /usr/(bin|local/bin)/hyprpm, plugin, ask

source = ~/dotfiles/modules/user/hyprland/modules/monitors.conf
source = ~/dotfiles/modules/user/hyprland/modules/env.conf
source = ~/dotfiles/modules/user/hyprland/modules/autostart.conf
source = ~/dotfiles/modules/user/hyprland/modules/general.conf
source = ~/dotfiles/modules/user/hyprland/modules/animations.conf
source = ~/dotfiles/modules/user/hyprland/modules/input.conf
source = ~/dotfiles/modules/user/hyprland/modules/keybinds.conf
source = ~/dotfiles/modules/user/hyprland/modules/windowrules.conf
source = ~/dotfiles/modules/user/hyprland/modules/plugins.conf
source = ~/dotfiles/modules/user/hyprland/modules/quickshell.conf
source = ~/dotfiles/modules/user/hyprland/modules/glass.conf


layerrule = blur true, rounding 25, rounding_power 2, match:namespace quickshell:control-center-tile
layerrule = blur true, rounding 17, rounding_power 2, match:namespace quickshell:control-center-footer

decoration {
  blur {
    size = 5
      passes = 2
  }
}
