$terminal = kitty
$fileManager = nautilus
$menu = vicinae toggle
$mainMod = WIN

permission = /usr/(bin|local/bin)/hyprpm, plugin, ask

source = ~/dotfiles/modules/user/hyprland/modules/monitors.conf
source = ~/dotfiles/modules/user/hyprland/modules/env.conf
source = ~/dotfiles/modules/user/hyprland/modules/quickshell.conf
source = ~/dotfiles/modules/user/hyprland/modules/autostart.conf
source = ~/dotfiles/modules/user/hyprland/modules/general.conf
source = ~/dotfiles/modules/user/hyprland/modules/animations.conf
source = ~/dotfiles/modules/user/hyprland/modules/input.conf
source = ~/dotfiles/modules/user/hyprland/modules/keybinds.conf
source = ~/dotfiles/modules/user/hyprland/modules/windowrules.conf
source = ~/dotfiles/modules/user/hyprland/modules/plugins.conf
source = ~/dotfiles/modules/user/hyprland/modules/glass.conf
