$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$mainMod = ALT

permission = /usr/(bin|local/bin)/hyprpm, plugin, ask

source = ~/dotfiles/modules/user/hyprland/modules/monitors.conf
source = ~/dotfiles/modules/user/hyprland/modules/env.conf
source = ~/dotfiles/modules/user/hyprland/modules/autostart.conf
source = ~/dotfiles/modules/user/hyprland/modules/general.conf
source = ~/dotfiles/modules/user/hyprland/modules/animations.conf
source = ~/dotfiles/modules/user/hyprland/modules/input.conf
source = ~/dotfiles/modules/user/hyprland/modules/keybinds.conf
source = ~/dotfiles/modules/user/hyprland/modules/windowrules.conf
source = ~/dotfiles/modules/user/hyprland/modules/plugins.conf
source = ~/dotfiles/modules/user/hyprland/modules/quickshell.conf
source = ~/dotfiles/modules/user/hyprland/modules/glass.conf

bind = $mainMod, Return, exec, kitty --override background_opacity=0

decoration {
    rounding = 7
    dim_special = 0.45
    shadow {
        enabled = true
        range = 70
        render_power = 3
        offset = 0 9
        scale = 1.0
        color = rgba(00000033)
        color_inactive = rgba(00000024)
    }
    blur {
        enabled = true
        ignore_opacity = true
        special = true
        noise = 0.00
        size = 1
        passes = 2
        vibrancy = 0.17
        glass_lensing = 58.0
        glass_edge_softness = 0
        glass_dimming = 0.16
        glass_tint_strength = 0.08
        glass_light_strength = 0.4
        glass_specular_strength = 2.0
        glass_shadow_strength = 0.35
        glass_ambient_strength = 0.18

        brightness = 1.2
        vibrancy_darkness = 1
    }
}
