add_newline = true

format = """
$username\
$hostname \
$directory\
$fill\
$time\
$line_break\
$character
"""

right_format = """
$git_branch
"""

[fill]
symbol = " "

[username]
show_always = true
style_user = "bold white"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = false
trim_at = "."
format = "[@$hostname](bold white)"

[directory]
style = "bold white"
format = "[$path]($style)"
home_symbol = "~"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = ""

[time]
disabled = false
time_format = "%I:%M:%S %p"
format = '[$time](bold white)'

[character]
success_symbol = "[>](bold white) [\\$](green)"
error_symbol = "[>](bold white) [\\$](red)"
vimcmd_symbol = "[<](bold white)"

[nodejs]
symbol = "⬡ "
style = "bold white"
format = "[$symbol$version]($style) "

[git_branch]
symbol = ""
style = "bold white"
format = '[$branch]($style)'
truncation_length = 999
truncation_symbol = ""

[git_status]
disabled = true
