[mgr]
prepend_keymap = [
  { on = "<Enter>",  run = "plugin smart-enter",                         desc = "Enter dir and quit, or open file" },

  # Preview
  { on = "F",        run = "plugin toggle-pane max-preview",             desc = "Maximize preview pane" },

  # Navigation
  { on = ["g","/"], run = "cd /", desc = "Root" },
  { on = ["g","d"],  run = "cd ~/Downloads",                             desc = "Downloads" },
  { on = ["g","v"],  run = "cd ~/Videos",                                desc = "Videos" },
  { on = ["g","P"],  run = "cd ~/Pictures",                              desc = "Pictures" },
  { on = ["g","m"],  run = "cd ~/Music",                                 desc = "Music" },
  { on = ["g","3"],  run = "cd ~/Graphics",                              desc = "Graphics" },
  { on = ["g","c"],  run = "cd ~/dotfiles",                              desc = "dotfiles" },
  { on = ["g","C"],  run = "cd ~/.config",                               desc = ".config" },
  { on = ["g","a"],  run = "cd ~/.cache",                               desc = ".cache" },
  { on = ["g","L"],  run = "cd ~/.local",                               desc = ".local" },
  { on = ["g","i"],  run = "cd ~/git",                                   desc = "Linux" },
  { on = ["g","I"],  run = "cd ~/.pi",                                   desc = "pi" },
  { on = ["g","H"],  run = "cd /mnt/hdd",                                desc = "hdd" },
  { on = ["g","S"],  run = "cd /mnt/ssd",                                desc = "ssd" },
  { on = ["g","D"],  run = "cd /mnt/dev",                                desc = "dev" },

  { on = ["g","p", "g"],  run = "cd /mnt/hdd/Projects/Linux",            desc = "Projects (HDD)" },
  { on = ["g","p", "p"],  run = "cd ~/Projects/",                        desc = "Projects (Local)" },

  { on = ["g","G", "h"],  run = "cd /mnt/hdd/Games",                                  desc = "HDD (Local)" },
  { on = ["g","G", "H"],  run = "cd /mnt/hdd/SteamLibrary/steamapps",                 desc = "HDD (Steam)" },
  { on = ["g","G", "s"],  run = "cd '/mnt/ssd/Program Files (x86)/Steam/steamapps'",  desc = "SSD (Steam)" },
  { on = ["g","G", "d"],  run = "cd /mnt/dev/SteamLibrary/steamapps/",                desc = "DEV (Steam)" },
  
  # Convert
  { on = ["m","p"],  run = "plugin convert -- --extension='png'",        desc = "to png" },
  { on = ["m","j"],  run = "plugin convert -- --extension='jpg'",        desc = "to jpg" },
  { on = ["m","w"],  run = "plugin convert -- --extension='webp'",       desc = "to webp" },

  # Actions
  { on = ["c","m"],  run = "plugin chmod",                               desc = "Chmod on selected files" },

  # Tabs
  { on = ["<C-w>"],  run = "plugin close-and-restore-tab close_to_left", desc = "Close tab, go left" },
  { on = ["<C-t>"],  run = "plugin close-and-restore-tab restore",       desc = "Restore closed tab" },

  # Trash
  { on = ["R","o"],  run = "plugin recycle-bin -- open",                 desc = "Open Trash" },
  { on = ["R","e"],  run = "plugin recycle-bin -- empty",                desc = "Empty Trash" },
  { on = ["R","D"],  run = "plugin recycle-bin -- emptyDays",            desc = "Empty by days deleted" },
  { on = ["R","d"],  run = "plugin recycle-bin -- delete",               desc = "Delete from Trash" },
  { on = ["R","r"],  run = "plugin recycle-bin -- restore",              desc = "Restore from Trash" },

  { on = ["0"], run = "plugin relative-motions 0", desc = "Relative motions" },
  { on = ["1"], run = "plugin relative-motions 1", desc = "Relative motions" },
  { on = ["2"], run = "plugin relative-motions 2", desc = "Relative motions" },
  { on = ["3"], run = "plugin relative-motions 3", desc = "Relative motions" },
  { on = ["4"], run = "plugin relative-motions 4", desc = "Relative motions" },
  { on = ["5"], run = "plugin relative-motions 5", desc = "Relative motions" },
  { on = ["6"], run = "plugin relative-motions 6", desc = "Relative motions" },
  { on = ["7"], run = "plugin relative-motions 7", desc = "Relative motions" },
  { on = ["8"], run = "plugin relative-motions 8", desc = "Relative motions" },
  { on = ["9"], run = "plugin relative-motions 9", desc = "Relative motions" },

  { on = ["<A-1>"], run = "tab_switch 0", desc = "Switch to tab 1" },
  { on = ["<A-2>"], run = "tab_switch 1", desc = "Switch to tab 2" },
  { on = ["<A-3>"], run = "tab_switch 2", desc = "Switch to tab 3" },
  { on = ["<A-4>"], run = "tab_switch 3", desc = "Switch to tab 4" },
  { on = ["<A-5>"], run = "tab_switch 4", desc = "Switch to tab 5" },
  { on = ["<A-6>"], run = "tab_switch 5", desc = "Switch to tab 6" },
  { on = ["<A-7>"], run = "tab_switch 6", desc = "Switch to tab 7" },
  { on = ["<A-8>"], run = "tab_switch 7", desc = "Switch to tab 8" },
  { on = ["<A-9>"], run = "tab_switch 8", desc = "Switch to tab 9" },
]
